language: r
r:
  - release
os:
  - linux
  - osx
branches:
  only:
    master

r_packages:
  - DiceKriging
  - randtoolbox
  - rgenoud
  - pbivnorm
  - rgenoud
  - foreach
  - doParallel
  - testthat
  - covr
cache: packages
    
addons:
  apt:
    packages:
      - libssh2-1-dev
      
before_install:
  - echo "$TRAVIS_OS_NAME"
  - echo "$TRAVIS_R_VERSION_STRING"
  - echo $PKG_TARBALL
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo chown -R $(whoami) /usr/local ; brew install libgit2; fi
  
after_success:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi

before_deploy:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
  # next line will allow to deploy in an existing release (here osx-linux). Before you need to put env: global: secure: XXX by running 'travis encrypt GH_TOKEN=<my github password> --add' from inside cloned repository
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then   git remote rm origin;  git remote add origin https://yannrichet:${GH_TOKEN}@github.com/KrigInvTeam/KrigInv.git;  git push --delete origin `git tag | grep -E 'osx-linux'`;   git tag -d `git tag | grep -E 'osx-linux'`;  git tag "osx-linux" --force; fi

deploy:
  provider: releases
  name: "osx-linux"
  api_key:
    secure: JZzQenI4jc+TNYm464h8p01FTkfAtkV68CHutsZoxPHjhZ6wNVaSiiJrP8ptRP+Us7AS6BawFn2nldBRUkbmMsXTChQ4aI1wLNiKN2cgQNTiukDe2J/kFjGMWSxdfzYOVJ/EJ/8Anl5XiiQGupZYloq+iMIFl6jcY52fpvsp2hsdxiexluqPy0WyfixsxSIENghVTZ9g1tiXW0odZtGNA6Luh1i4zPvUWnGib2mXg7bzYcMh6BatE5D1U06PcmjwQGOvxWMFRQB25WJZz8KUwE6JvevPC18H3o5RUVCygHKWRM8TTkAU/QuLxkszDcyth8yBRIfkHvO3FgMENJBX2t6px42rE2qsmrJDVIriCJYd1rjgxYID6fpIJXxXRXOT3BGmp0wwrmCAcpdLntOn7taCRsmfxV3+yHX/9v0baDcZcjEUgcprt7qVxAl/gS/j+r3ICHeuC9QjX7qAyCFVjOXdx+uTSbczAsKTlUZFD2FWULHVMwXIs/sp0vO5Rf6JHD3chaO4P02ChBq5G9j91+n337J3VIjbuiZjsSY2HQfu3CpLD9FeZAKQxPmoMT0hcimdHTHlbYzHs3+or990IZE9882MSiTNtEtTUSme7G+/x5s2K9/O1bSfibNrfK0Xr9s1AsgX2WyDehBewBfPFdd4S79vI3F3tXYhdT7Z84Y=
  file_glob: true
  file: KrigInv*.t*gz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    except: 
      - windows
      - linux
    condition: "$TRAVIS_R_VERSION_STRING = release"

env:
  global:
    secure: lLEVnXK6POa+AQzvsvdJJLVxum3xPfIlqoAvhK+LPsOuhWFBeAxGsOhqNL6yxdV+Q0yUtwUV848Vyqd1TOFQE1py8Ict5pd/KUD+Ob5REv+RPRg/1A7hT9q574Jg2Fv18iyJImSwBmHNGwWW2wEfPTqRY21Ymb1lsNdSMuqBASA2vouX5Vxe1PN/n8t/tDkbyUK/O5YDqq4559qdeIO+hmo6YGFMe70NHZM790omQWuX2VB2WziXSsSyKWXaLrxV+tApWZo/PJ2HxP7YzyjFdauL/tpTdcLNzWhBf3vhFEiajnogH1agj0bZNyvdFOnYjm1QJfq+S+wBZEeL2gePbt7W//jCPLaQ/Lz+SfvY4Rx4N2X44pN+QqZcPJe31zZEqcFYxEwF4CcIMYBoDbIej6dXNIe9NDVuiz5cqeKJyPkT6mSuJmzAQekV+lFNFrpYd2Ze3r9r2lvb78+XNZ8jQgznyv+o/mXP2sYmPRF50P9WJ2kGBYHaKyKrQMrqDg5nTYzyKCcIzvRTeCxO+PKSWELlf2pGMwJT2NY/A308t3L7J705RYkeBQ3zReq12KAVZtSWm71bRF5937/yW4pmNl+0gdo18U/Ksyh7n81VVsWW4G6L3ecI+/48g29j+eW9XHM8MOkIMp8KhTHQUySI2/pKf6/BfQAZmjaZ4yY8PcE=
